spring:
    prefiles:
    active: dev


---
server: 
    port: 8001
# spring
spring:
  prefiles: dev
  application:
    name: springcloud-provider-dept


# eureka的配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      
---

server: 
    port: 8002
# spring
spring:
  prefiles: test
  application:
    name: springcloud-provider-dept


# eureka的配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/