spring: 
  profiles: 
    active: dev
    
---

server:
  port: 8001
mybatis:
  type-aliases-package: com.stu.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# eureka的配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance: #修改名字
    instance-id: spring-provider-dept8001

info:
  app.name: stu.springcloud
  company.name: blog
  
---

server:
  port: 8001
mybatis:
  type-aliases-package: com.stu.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring
spring:
  profiles: test
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db0?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# eureka的配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance: #修改名字
    instance-id: spring-provider-dept8001

info:
  app.name: stu.springcloud
  company.name: blog  
